### ISSUE TITLE
undefined method `name' in 0.9.6 using Sequel

### ISSUE THREAD

**Issue by MatzFan** [SamSaffron/memory_profiler#36] opened 2016-08-24 16:22 UTC
Related to #27 I guess - though I have the object this time:
`/Users/me/.rvm/gems/ruby-2.3.1/gems/memory_profiler-0.9.6/lib/memory_profiler/helpers.rb:28:in 'lookup_class_name': undefined method 'name' for #<Sequel::SQL::Identifier @value=>:class> (NoMethodError)`

This appears when I am using derailed_benchmarks to list the [objects created at require time](https://github.com/schneems/derailed_benchmarks#objects-created-at-require-time). My app is a Padrino app using Sequel ORM.

It seems to be caused by Sequel::SQL::VirtualRow objects. These subclass BasicObject & return another object subclassing Object (Sequel::SQL::Identifier) when :class is called on them.

So the question: is memory_profiler expected to deal with objects subclassing BasicObject & if so how (Jeremy Evans, the maintainer of Sequel [asked me this question](https://groups.google.com/forum/#!topic/sequel-talk/WvRTzb8u0kY))? If not, would you accept a PR to fix the issue - I'd propose rather than calling :class on an unknown object [using this clever trick](https://stackoverflow.com/a/18621313/4114896) instead - which works on objects sub-classed from BasicObject.

Many thanks

Bruce

**Comment by dgynn** [comment] 2016-08-24 21:10
That is an interesting case and clever trick. Thanks for finding them. There are some unreleased fixes that deal with class name lookups. If you point your Gemfile to the current master for memory_profiler you'll be able to get past that exception.

Currently, memory_profiler deals with BasicObject (and subclasses) by reporting them as having an `<<Unknown>>` class. The trick you pointed out could allow us to do better reporting for BasicObjects. I'm trying out a patch for that now.

This may or may not help with the Sequel issue. The problem isn't so much that the `Sequel::SQL::VirtualRow` is a BasicObject. It is that it also implements `method_missing` so it is responding to `.class` with something that isn't a Class. So in the worst case, some Sequel memory allocations might be marked as `<<Unknown>>` class but most of them will report correctly.

**Comment by MatzFan** [comment] 2016-08-24 21:30
Great, glad you've already a fix for it. As I'm relying on the derailed_benchmarks gem, I'll patch that until your next release is out & derailed_benchmarks uses it.

FYI, according to the accepted answer in that SO question `ActiveSupport::Duration` also implements the `method_missing` strategy, making introspection difficult

**Comment by dgynn** [comment] 2016-08-24 21:36
This will work with derailed_benchmarks if you want to try it out now. Just update your Gemfile to this...

```ruby
group :development do
  gem 'derailed_benchmarks', '1.3.1'
  gem 'memory_profiler', :github => 'SamSaffron/memory_profiler', :branch => 'master'
end
```

**Comment by MatzFan** [comment] 2016-08-25 07:34
Perfect, thanks.

**Comment by SamSaffron** [comment] 2017-02-07 15:47
0.9.7 is long ago released :)

**Closed by SamSaffron** 2017-02-07 15:47 UTC
