### ISSUE TITLE
MemoryProfiler falsely report retained string

### ISSUE THREAD

**Issue by chopraanmol1** [SamSaffron/memory_profiler#57] opened 2018-09-06 09:57 UTC
```
MemoryProfiler.report{ 200.times{|i| "SOME RANDOM TEXT#{i}: SOME Value".dup } }.pretty_print
```
The above code result into
```
Total allocated: 41600 bytes (800 objects)
Total retained:  17600 bytes (200 objects)
```

I've tried running same code without memory_profiler and in infite loop and it doesn't increase memory.

The result changes for short string:
```
MemoryProfiler.report{ 200.times{|i| "TEXT#{i}: Value".dup } }.pretty_print
```
```
Total allocated: 24000 bytes (600 objects)
Total retained:  0 bytes (0 objects)
```

**Comment by SamSaffron** [comment] 2018-09-07 06:42
I am having trouble reproducing this, what platform / ruby version are you on?

**Comment by chopraanmol1** [comment] 2018-09-07 07:58
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

I've also tried on different ruby version which resulted the same.

Upon further inspection it seems like ruby allocated an extra frozen string while duplicating long string with interpolation. And this frozen strings are reported as retained object. I'm not sure if this expected behavior or should be considered bug on memory_profiler or ruby side. If you think this is expected behavior or bug on ruby side then feel free to close this issue.

As this frozen string can be GC'ed and is not referenced by anything, I think it should not be reported as retained string since MemoryProfiler explicitly calls GC.start.

**Comment by william101** [comment] 2018-09-10 20:41
This probably has something to do with `Pry`. I can only reproduce this when run inside a `pry` console but not in `irb` or a `.rb` file

`pry`:
```
$ RBENV_VERSION=2.4.4 pry
[1] Memory_profiler(GEM)> require "memory_profiler"
=> true
[2] Memory_profiler(GEM)> MemoryProfiler.report{ 200.times{|i| "SOME RANDOM TEXT#{i}: SOME Value".dup } }.pretty_print
Total allocated: 41600 bytes (800 objects)
Total retained:  17600 bytes (200 objects)
```

`irb`:
```
$ RBENV_VERSION=2.4.4 irb
irb(main):001:0> require "memory_profiler"
true
irb(main):002:0> MemoryProfiler.report{ 200.times{|i| "SOME RANDOM TEXT#{i}: SOME Value".dup } }.pretty_print
Total allocated: 41600 bytes (800 objects)
Total retained:  0 bytes (0 objects)
```

`.rb`:
```ruby
require 'memory_profiler'
MemoryProfiler.report{ 200.times{|i| "SOME RANDOM TEXT#{i}: SOME Value".dup } }.pretty_print
```
```bash
$ RBENV_VERSION=2.4.4 ruby -v test.rb 
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
Total allocated: 41600 bytes (800 objects)
Total retained:  0 bytes (0 objects)
```

@chopraanmol1 any chance you use a pry console to run your example?

**Comment by SamSaffron** [comment] 2018-09-10 23:40
@dgynn any chance you can have a look 

I recall we used to run GC in a loop till it  stopped releasing stuff, per: https://github.com/SamSaffron/memory_profiler/commit/764bd73d829422bb37c6906bc28eb74fcdc5f282 but I don't recall exactly why we stopped doing this.

**Comment by SamSaffron** [comment] 2018-09-10 23:41
oh... this happened to it: https://github.com/SamSaffron/memory_profiler/commit/201609e02cd08d878d4dff5f053355db69fd2992#diff-80e5ea47d42d3b7465152ceeae9fd0ef 

@dgynn maybe we bring this back?

**Comment by dgynn** [comment] 2018-09-11 03:31
I am able to reproduce this and it is an issue created by the recent change (#52) to use a string cache to reduce memory allocation with big strings.

@chopraanmol1 is right that there is a extra frozen string being created when a long string (longer than 23 characters) is created or duplicated. When we create a copy of that string to store in the internal statistics, we create **another** reference to that shared, frozen string. The internal statistics cause the shared string to be retained.

I'll have a fix for this shortly.

**Comment by chopraanmol1** [comment] 2018-09-11 05:05
@william101 I'm able to reproduce in both irb console and .rb file without requiring of pry.

**Comment by SamSaffron** [comment] 2018-10-04 05:30
I think the root issue here for a bunch of pain is due to fstring magic:

```
require 'objspace'

x = "hello" * 10_000
puts ObjectSpace.memsize_of(x)
# 50041

x1 = "hello" * 10_000
puts ObjectSpace.memsize_of(x1)
# 50041

y = {}
y[x] = "test"

puts ObjectSpace.memsize_of(x)
# 40

_x2 = -x1
puts ObjectSpace.memsize_of(x1)
# 40

```

This is really messing up our reporting creating all these fstrings during analysis. I am going to have to revert this for now @dgynn

**Comment by SamSaffron** [comment] 2018-10-04 06:06
OK, I did this now to avoid large under reporting of memory 

https://github.com/SamSaffron/memory_profiler/commit/b99ccaf32379f46dc3dc2ea4c40bff8382324015

**Comment by dgynn** [comment] 2018-10-04 06:19
Yes! That makes great sense. We could certainly be underreporting string sizes based on the string cache lookup creating shared fstrings.
I do think #59 and #58 together resolve GC of retained strings caused as a side-effect of internal memory_profiler code.

**Closed** 2018-10-07 19:05 UTC

**Comment by casperisfine** [comment] 2019-03-22 12:37
I'm wondering wether this bug actually have been fixed. Using `memory_profiler` master branch I get nonsensical reports about string.

Here's the report I get:

```
retained objects by location
-----------------------------------
    977209  /tmp/bundle/ruby/2.5.0/bundler/gems/rails-25620f91ca0a/activesupport/lib/active_support/dependencies.rb:433
    927734  /tmp/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.rb:456
    367262  /tmp/bundle/ruby/2.5.0/bundler/gems/rails-25620f91ca0a/activesupport/lib/active_support/dependencies.rb:443
```

That first entry correspond to `ActiveSupport::Dependencies.search_for_file`:

```ruby
    def search_for_file(path_suffix)
      path_suffix += ".rb" unless path_suffix.ends_with?(".rb")

      autoload_paths.each do |root|
        path = File.join(root, path_suffix)
        return path if File.file? path
      end
      nil # Gee, I sure wish we had first_match ;-)
    end
```

Then elsewhere in the same report:

```
allocated objects by location
-----------------------------------
.....snip
   2149782  /tmp/bundle/ruby/2.5.0/bundler/gems/rails-25620f91ca0a/activesupport/lib/active_support/dependencies.rb:432
   1591144  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.3/lib/graphql/define/instance_definable.rb:205
   1365426  /tmp/bundle/ruby/2.5.0/bundler/gems/rails-25620f91ca0a/activesupport/lib/active_support/dependencies.rb:443
   1074891  /tmp/bundle/ruby/2.5.0/bundler/gems/rails-25620f91ca0a/activesupport/lib/active_support/dependencies.rb:433
```

So if I believe that profile, `search_for_file` allocated `1074891` objects (pretty sure that is accurate given the size of our load path), and `977209` (90%) of them would have been retained.

It's so surprising that I've put some instrumentation in there, and I can say for sure this method is called less than 3000 times, so even if all the strings it returns were retained somewhere it can't possibly retain more than 3k objects.
